INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:05', '', '<p>Theresa May has declared that tomorrow''s vote on her Brexit deal will be delayed so she can return to Brussels to plead for better terms on the Irish backstop in a bid to satisfy...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/brexit-latest-news-vote-theresa-mays-deal-air-rivals-eye-leadership/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:06', '
Jeremy Corbyn urged to call no confidence vote in Government as SNP tells Labour leader ''this shambles can''t go on''
', '<p>Jeremy Corbyn has been urged to trigger a vote of no confidence in Theresa May as Nicola Sturgeon said the SNP was willing to form an alliance with Labour to “stop Brexit”.The Labour leader was under increasing pressure from his own MPs to pull the trigger on a formal vote in the House of Commons as Mrs May’s Government descended into chaos.Ms Sturgeon, the Scottish First Minister and leader of the SNP, said her 35 MPs would support Mr Corbyn if he lodged a motion of no confidence and that she was willing to work with Labour to bring about a second referendum.Meanwhile, dozens of Labour MPs signed a letter to Mr Corbyn urging him to act.But Shami Chakrabarti, the shadow attorney general and...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/jeremy-corbyn-urged-call-no-confidence-vote-government-snp-tells/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:07', '
The resignation game: Would you have made it as far as Theresa May or quit by now?
', '<p>It has been another damaging week in a long line of damaging weeks for Theresa May - and it''s only Monday evening.Would you have made it as far as the Prime Minister? Or would you have quit long ago?Put yourself in her shoes by using our interactive game, below, to play out the biggest setbacks Mrs May has encountered so far. Play our game and then have your say in the comments.Would you have resigned after the general election last year? Or would you, like Mrs May, be still around today? At times it seems as though Mrs May has a superhuman ability to ignore the noise around her and dig her heels in for what she believes is right.Despite many voicing dismay at her plans - including two Brexit...</p>', 'https://www.telegraph.co.uk/politics/2018/11/16/resignation-game-would-have-made-far-theresa-may-quit-now/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:08', '
''She is going to kill the Conservative Party'' - Telegraph readers react to Brexit vote delay  
', '<p>After repeated assurances, from everyone from Michael Gove to the Prime Minister''s Official Spokeswoman, that the meaningful Brexit vote would go ahead on Tuesday evening as planned, Theresa May has delayed the vote in Parliament.Mrs May is understood to have held an emergency conference call with her Cabinet this morning, amid claims she was under increasing pressure from ministers and her chief whip to delay the ''meaningful vote''. Her allies feared that a major defeat in the Commons, possibly by over 100 votes, would make Mrs May''s position as party leader untenable. Telegraph readers were swift to react to the news of a possible delay, with many interpreting the decision as an act of cowardice...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/going-kill-conservative-party-telegraph-readers-react-brexit/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:08', '
What does the ECJ ruling on Article 50 mean for the Brexit deal?
', '<p>The European Court of Justice has ruled that Britain can unilaterally cancel Brexit, without getting the permission of other EU countries first. But what does that decision mean for the UK, the EU and Theresa May’s (now delayed) Brexit deal?EU judges in Luxembourg said that Britain could stop the Article 50 process before the 29 March 2019 Brexit deadline and remain in the EU on the same terms as before the referendum.The only condition to reverse the two year negotiation period is that it follows “a democratic process”, meaning a parliament decision, a general election or a referendum.Mrs May insists she will not revoke Brexit and the likes of Michael Gove and Jeremy Hunt have downplayed...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/does-ecj-ruling-article-50-mean-brexit-deal/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:09', '
As the Brexit ''meaningful vote'' in Parliament is delayed - what are the next steps for Theresa May?
', '<p>After months of negotiations, the Brexit deal was due to be voted upon tomorrow, in order for the United Kingdom''s Parliament to approve or reject Theresa May''s controversial plan.However, the prime minister has dramatically called off the "meaningful vote", today, in the face of what had been expected to be a significant defeat at the hands of rebel MPs.A Government source confirmed that the vote was being pulled, with the Prime Minister due to inform the House of Commons in an oral statement at 3.30pm where she is expected to confirm that she intends to seek further concessions from Brussels to try to win over rebellious backbenchers.But what does all this mean for the "meaningful vote"...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/time-does-parliament-vote-brexit-deal-tomorrow-meaningful-vote/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:10', '
Who could replace Theresa May as the next Tory leader and Prime Minister? Runners and riders
', '<p>Theresa May''s leadership is under intense pressure after she dramatically called off the crucial "meaningful vote" on her controversial Brexit deal.The Prime Minister apparently made the decision after it became clear she was due to face significant defeat at the hands of rebel MPs on Tuesday, leaving her political future in doubt. A Government source confirmed that the vote was being pulled, with the Prime Minister due to inform the House of Commons in an oral statement at 3.30pm.Mrs May''s hastily-arranged oral statement is widely expected to confirm that she intends to seek further concessions from Brussels to try to win over rebellious backbenchers.But as the Brexit chaos continues and rumours...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/runners-riders-could-replace-theresa-may-forced-downing-street/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:11', '
How Theresa May''s Tory government is the most divided of the post-war era 
', '<p>Theresa May is under intense pressure as she attempts to secure a Brexit deal with the EU, not least from her own party, who are the most divided Tory government of the post-war era.At least one MP has rebelled in 28 per cent of parliamentary divisions since the surprise snap election in 2017, new research has found.This is the highest proportion of rebellions that any Conservative leader has faced while in power since World War Two.To avoid yet another defeat on Tuesday, May postponed a major vote on her Brexit deal - which appeared to be heading towards a heavy defeat - on Monday morning.The research, conducted by political science academics Professor Philip Cowley, Dr Mark Stuart and Professor...</p>', 'https://www.telegraph.co.uk/politics/2018/08/15/theresa-mays-divided-tory-government-post-war-era/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:12', '
Norway plus, second referendum or EU rescue: what are all the options if Theresa May''s Brexit plan fails?
', '<p>It is the Brexit question on everyone’s lips - with Theresa May’s withdrawal plan doomed to failure at Tuesday’s meaningful vote, what happens next in the chaos that is Britain’s departure from the EU?With no consensus in parliament for any alternative option, we war game the possible scenarios in a bid to understand all the options available to the Government in the seemingly inevitable event of a huge rebellion in three day’s time.Seven ministerial resignations down since the deal was agreed and with outright mutiny brewing on the backbenches, Mrs May could have no choice but to call a last minute meeting with Michel Barnier in a final roll of the dice to remove the universally...</p>', 'https://www.telegraph.co.uk/politics/0/norway-plus-second-referendum-no-deal-eu-rescue-likely-brexit/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:13', '
What is Article 50? The only explanation you need to read
', '', 'https://www.telegraph.co.uk/politics/0/what-is-article-50-the-only-explanation-you-need-to-read/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:14', '
What is the Brexit deal, and what will happen after Parliament votes?
', '<p>Parliament is set to vote on Theresa May''s Brexit deal on Tuesday evening, with the Prime Minsiter expected to suffer a heavy defeat. The deal on the table has been signed off by European leaders and came after 19 months of negotiation. It includes a Brexit divorce settlement (the Withdrawal Agreement) of nearly 600 pages which, Mrs May says, delivers on her pledge to take back control of laws, borders and money. A Political Declaration has also been agreed which outlines aspirations for the future trading relationship between the EU and the UK. Only 26 pages long, it sets out the ambitions for the trade talks to come. It is not legally binding, although both sides commit in the Withdrawal...</p>', 'https://www.telegraph.co.uk/politics/0/brexit-deal-will-happen-parliament-votes/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:15', '
What is the Brexit backstop, and how might it bring down the British Government?
', '<p>For Brexiteers, the Irish "backstop" has become a dirty word, handcuffing the UK to the EU’s customs union and taking away Britain’s chance to strike trade deals around the world for the foreseeable future.  When the history of Brexit is written, there will be long arguments over whether the ‘backstop’ could have been avoided, but even before the Brexit vote, it was clear that Ireland was going to present a major impediment to the UK’s departure from the EU.The backstop has its origin in the 1998 Good Friday Agreement which created an "invisible" border between Northern Ireland and the Republic as part of the peace settlement between Unionist...</p>', 'https://www.telegraph.co.uk/politics/0/brexit-what-is-irish-backstop-deal-meaning-explained/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:16', '
The Real Brexit Debate, Channel 4, review: the full extent of the parliamentary divide laid bare
', '<p>After the BBC and ITV failed to persuade Theresa May and Jeremy Corbyn to battle over their Brexit plans on their channels, Channel 4 has sought to show that it isn’t too hard to bring politicians together to argue about the best way forward.As the only political punch-up broadcast this weekend, “The Real Brexit Debate” was meant to be - as host Krishnan Guru-Murthy put it, “the debate we believe the British public deserves”.Did it live up to that billing? Channel 4 didn’t have the two people broadcasters had been fighting to nail down for weeks, as Guru-Murthy acknowledged at the end sheepishly: “Why couldn’t Theresa May and Jeremy Corbyn come?”However, it tried to make up for it with four...</p>', 'https://www.telegraph.co.uk/tv/2018/12/09/real-brexit-debate-review/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:17', '
Anton du Beke and Helen Skelton try out tennis speed training exercises from Judy and Jamie Murray
', '', 'https://www.telegraph.co.uk/tennis/challenges/tennis-speed-training/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:17', '
From traditional to trendy, seven Christmas dinner ideas to impress your guests
', '', 'https://www.telegraph.co.uk/food-and-drink/christmas-dinner-ideas/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:19', '
What goes into your beauty products?
', '', 'https://www.telegraph.co.uk/beauty/trusted-skincare/cosmetic-ingredients/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:19', '
Brexit latest news: Cabinet ministers demand answers as Chief Whip admits May will lose Tuesday’s vote
', '<p>Cabinet ministers told Theresa May on Thursday night that she must come up with an 11th hour plan to get her Brexit deal through the Commons as the Chief Whip admitted she will lose Tuesday’s vote.The Prime Minister was confronted in Downing Street by Amber Rudd and other senior ministers who demanded to know what she intends to do to salvage the vote, and her...</p>', 'https://www.telegraph.co.uk/politics/2018/12/06/brexit-latest-news-economy-dominate-day-three-debate-whips-seek/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:20', '
Theresa May tells Cabinet she will not postpone vote on Brexit deal as MPs say they would block any delay
', '<p>Theresa May has denied she could postpone the meaningful vote on her Brexit deal as MPs said any bid to push back the showdown in the House of Commons would fail.The Prime Minister has been advised by members of her Cabinet to delay asking MPs to deliver their judgment on her deal amid fears a crushing defeat could sink her Government.Mrs May indicated on Thursday she had no intention of putting off the vote as it emerged she would need the agreement of MPs to stop it from going ahead.The vote on December 11 was effectively set in stone by MPs at the start of the debate on the Prime Minister’s Brexit deal on Tuesday and any new timetable would have to be backed by the Commons.But with the...</p>', 'https://www.telegraph.co.uk/politics/2018/12/06/theresa-may-tells-cabinet-will-not-postpone-vote-brexit-deal/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:21', '
What the secret Brexit legal advice says and how it differs from what Theresa May told us before
', '<p>The Government has been forced to publish the six-pages of legal advice that Geoffrey Cox, the Attorney General, gave the Cabinet about the customs backstop.Ministers were forced to publish the advice after being found in contempt of Parliament following a historic vote in the Commons on Tuesday.The DUP said the advice was "devastating", while Tory Eurosceptics said it was significantly at odds with the Government''s public statements on the backstop.What the Government said:In the Commons, Geoffrey Cox conceded that the backstop could be "indefinite" but repeatedly insisted that the backstop is a "temporary solution",...</p>', 'https://www.telegraph.co.uk/politics/2018/12/05/theresa-mays-secret-brexit-legal-advice-says-differs-told-us/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:22', '
How the value of the pound has been affected by Brexit negotiations
', '<p>The value of the pound has plunged further against the Euro today as Theresa May postponed the meaningful vote on her Brexit withdrawal deal.Today''s drop is just the latest in a long line of fluctuations in the value of the pound during Brexit negotiations. Last month Sterling suffered the biggest plunge in a year against the euro following the resignations of Brexit Secretary Dominic Raab and Work and Pensions Secretary Esther McVey.The news that Theresa May had reached an agreement with the EU over the UK''s withdrawal had prompted a surge in the pound as the possibility of a "no deal" scenario lessened slightly.But in the wake of the cabinet resignations, the GBP fell from a high of 1.15...</p>', 'https://www.telegraph.co.uk/business/2018/11/14/value-pound-has-affected-brexit-negotiations/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:23', '
Hollywood Bowl unfazed by Brexit uncertainty after dividend hike
', '', 'https://www.telegraph.co.uk/business/2018/12/10/hollywood-bowl-unfazed-brexit-uncertainty-dividend-hike/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:24', '', '<p>Theresa May has pulled the ‘meaningful vote’ on her Brexit deal in order to go through the motions of wringing some final concessions from Brussels - when Brussels has been saying for weeks now that there are no fundamental concessions to be had.Certainly not on the Withdrawal Agreement, a position the Commission spokesman reiterated again today. “We have an agreement on the table,” he said. “This deal is the best and only deal possible. We will not renegotiate.” You cannot get much clearer than that.  So what is the game here? Essentially, May is buying herself some more time. The plan, she told Cabinet ministers, is to demand a “legally binding assurance” that the Irish backstop is not permanent....</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/fudge-prime-minister-theresa-may-seeks-binding-assurances-eu/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:24', '', '<p>“The timing is sublime. A bright light has switched on above an Exit sign.” So said SNP MEP Alyn Smith in reaction to the judgement of the European Court of Justice (ECJ) that Britain could, after all, unilaterally rescind its notice of intention to leave the EU and carry on with its membership under existing terms – as if nothing had happened.    It is not hard to see how Remainers now see events playing out. With Theresa May having kicked her withdrawal deal into touch, the Commons unites to demand that the issue be settled by a second referendum – with Remaining in the EU an option on the ballot paper. Disgusted by the chaos of Brexit and fearful of about the apocalyptic warnings of a ‘no...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/ecj-ruling-just-tonic-brexiteers-need/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:25', '', '<p>Cabinet ministers could be forgiven for feeling surprised by Theresa May informing them this morning that she would "defer" the Commons vote on her Brexit deal in order to avoid a "notable" defeat.The Prime Minister had been adamant until today that the vote would happen tomorrow, with her ministers sent out to ram that home. "I don''t think there is any chance of pulling the vote," Sajid Javid told the Today programme last Monday. "I just don''t see that happening."The Home Secretary was not going out on a limb, as the Prime Minister herself was asked by the BBC later that week on Thursday whether the vote would be delayed and she said "no". Her spokesman echoed that faithfully, declaring: "It''s...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/theresa-mays-panicky-brexit-vote-delay-makes-harder-anyone-trust/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:26', '', '<p>Dear MPsYou’re having a difficult time at the moment, and the last thing I would want to do is make life even worse for you. I am very aware that the pressures on you land not just on your shoulders but on those of your staff and, most importantly, your families. Yes, we all know that you knew what you were letting yourself in for when you chose to stand for election to the House of Commons, but let’s face it – you didn’t quite picture the current situation, did you? Well, none of us did.Difficult votes are nothing new, of course – it’s kind of the point of your job. But there’s difficult, and then there’s Brexit. There is, however, a third category: Iraq.When I was first elected to parliament,...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/dear-mps-job-make-unpopular-decisions-now-just-get/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:27', '', '<p>In a newspaper interview yesterday, Mrs May held out the prospect, if only MPs would vote for her Brexit deal, of having the whole thing sewn up by Christmas. Attached to her interview were various anonymous briefings. These suggested that otherwise Parliament might have to sit through Christmas for the first time since 1656 and/or – as it was rather oddly put – “Jeremy Corbyn would be able to visit the Queen over Christmas” (with a view to becoming Prime Minister).It is indeed woeful to think of MPs holed up in the House of Commons wearing paper hats and trying to force the catering department to produce some turkey for them on the Feast of the Nativity. It is more profoundly upsetting to think...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/christmas-no-mrs-may-bad-deal-will-prolong-battle-brexit/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:28', '', '<p>What an irony!  Gina Miller saves Brexit – at least for now.  When the doughty Remain campaigner persuaded the Supreme Court that parliament should have a significant vote on the Brexit deal, many lawyers thought this decision was wrong in law.  But without it, the Prime Minister would have been able to push through her Withdrawal Agreement: Brexit In Name Only.This was a significant change in constitutional practice.  Making and ending treaties was traditionally a matter for the Crown – the executive.  In the early 18th century, the French philosopher Montesquieu made British practice into a theory – the ‘separation of powers’ -- which he considered necessary for liberty.  The American rebels...</p>', 'https://www.telegraph.co.uk/opinion/2018/12/10/argue-people-didnt-understand-brexit-vote-undermines-parliaments/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:29', '', '<p>I have now heard much of the parliamentary debate on the Withdrawal Agreement – and it has hit me that the gloomier commentary is wrong. Yes it is true that Parliament is divided. Yes, there are competing visions for the future; and there are quite a few MPs who would like to reverse the result of the referendum. But it is just not true that there is no single viewpoint that would carry the majority of the House.I have listened to MPs on all sides, Labour and Tory, Leavers and Remainers, speaking passionately for their constituents and for their democracy – and there is one position that brings together a large...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/must-take-brussels-steel-unity-pms-deal-voted/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:30', '', '<p>Last week, Parliament reasserted its sovereignty over Government in a “glorious vote”, according to some MPs. I disagree. I find a darker and more cynical motive behind it. The political classes are increasingly paying lip service to the vote while planning to prevent it.The elites are retaking control of our national decision-making using the natural political gravity of a “Remain” House of Commons. Parliament has declared Government to be in contempt of Parliament. But if it thwarts Brexit, Parliament risks being in contempt of the British people.At the heart of this impending democratic car crash...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/arrogant-remainer-mps-steering-us-towards-democratic-car-crash/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:32', '
Theresa May has to say ''no'' to Brussels next week to save her job - and Brexit, says Dominic Raab
', '<p>Theresa May could have to resign next week over Brexit, her former minister in charge of her talks has admitted.Asked on this week’s Chopper’s Brexit Podcast if Mrs May will have to quit next week, Dominic Raab said: “I hope not. I hope she can instead show the resolve, grit and determination which is her at her best.“She has got to be willing finally to say to Brussels ‘no’. If she can do that then she can still turn this round.”Mr Raab said he thought the deal would be voted down, adding “if the deal is voted down I would like the Prime Minister to go back to Brussels and set out our best final offer”.This would address the backstop issue - which ties the UK to EU regulations after Brexit...</p>', 'https://www.telegraph.co.uk/politics/2018/12/07/theresa-may-has-say-no-brussels-next-week-save-job-brexit/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:33', '
Jacob Rees-Mogg: Britain will have a general election if Theresa May''s Brexit deal goes through Parliament
', '<p>Theresa May will be forced to call a general election if she manages to push her Brexit deal through Parliament, Jacob Rees-Mogg has said.The chairman of the European Research Group of Tory MPs dismissed claims that the Prime Minister could lose by a 200 majority when MPs vote on the deal on December 11.But he warned on Chopper’s Brexit Podcast that even if Mrs May persuades enough MPs to back her deal, she would face an immediate vote of no confidence called by the Democratic Unionist Party, whose 10 MPs are supporting the Government.He said: "What do I think is going to happen? Expectations on meaningful vote are getting completely out of hand, the Government will have a very large vote,...</p>', 'https://www.telegraph.co.uk/politics/2018/11/28/jacob-rees-mogg-britain-will-have-general-election-theresa-mays/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:35', '
Theresa May’s Brexit deal is the product of a coup d’état, says Peter Lilley
', '', 'https://www.telegraph.co.uk/politics/2018/11/22/theresa-mays-brexit-deal-product-coup-detat-says-peter-lilley/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:36', '', '', 'https://www.telegraph.co.uk/politics/2018/11/27/football-clubs-should-run-like-businesses-good-communities/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:37', '', '', 'https://www.telegraph.co.uk/politics/2018/11/25/police-moped-crime-strategy-worrying-politicians-cheering/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:38', '', '', 'https://www.telegraph.co.uk/politics/2018/11/15/students-dont-need-nannying-universities-shame-drinking-less/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:40', '', '', 'https://www.telegraph.co.uk/politics/2018/11/14/female-sexual-liberation-available-free-market/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:41', '
DUP tells Tory Brexiteers ''reject the deal and we will not bring down the Government''
', '<p>The DUP has assured Brexiteers it will not bring down the Government if they reject Theresa May’s Brexit deal next week. Nigel Dodds, the DUP Westminster leader, told a meeting of Tory Brexiteers on Wednesday night that his party would support the Government in a confidence vote if the draft withdrawal agreement is thrown out by Parliament next week.However, it will withdraw its support if Mrs May’s deal goes through - wiping out her working majority in Parliament and raising the spectre of a general election.Mr Dodds warned the Prime Minister that there would be "implications" if her deal "squeaks" through Parliament next week. Whilst he refused to say whether the party could continue to...</p>', 'https://www.telegraph.co.uk/politics/2018/12/05/dup-pledges-conditional-support-theresa-may-plots-brexit-plan/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:42', '
Sisterhood and squabbling: A hidden history of Labour''s women
', '<p>The Labour Party was born on a damp Tuesday in February 1900, when a group of like-minded socialists gathered in a London hall to set up a body capable of getting working-class men elected to Parliament. No women officiated at the birth, but a handful watched silently from the public gallery. Six years later, 29 Labour candidates were elected to the House of Commons, and a new political force was primed for power. From its inception, the party reeked of masculinity. Its foundations were dominated by names such as Keir Hardie and Ramsay MacDonald, and its history was forged in smoke-filled rooms...</p>', 'https://www.telegraph.co.uk/books/non-fiction/sisterhood-squabbling-hidden-history-labours-women/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:43', '
Foreign investors erect a firewall against future Corbyn government
', '<p>Rising fears of a Corbyn government are prompting foreign investors in Britain to prepare legal countermeasures to prevent their assets being nationalised against their wishes.The Sunday Telegraph has learned that the Canada Pension Plan Investment Board (CPPIB), a major infrastructure investor, is in talks aimed at putting its one-third stake in Anglian Water, acquired for £2.3bn in 2006, beyond the reach of a potential Labour government.City sources said CPPIB, one of the world’s biggest pension funds, is in talks to transfer its Anglian shares to a holding company based in Hong Kong. The work is underway amid Brexit-related chaos in Westminster that it is feared could trigger a General Election...</p>', 'https://www.telegraph.co.uk/business/2018/12/08/foreign-funds-shoring-defenses-against-corbyn-utility-grab/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:45', '
Thousands protest against Tommy Robinson''s ''Brexit Betrayal'' march in London 
', '', 'https://www.telegraph.co.uk/politics/2018/12/09/thousands-protest-against-tommy-robinsons-brexit-betrayal-march/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:46', '
Ukip civil wars: Nigel Farage calls for Gerard Batten to be sacked over hiring of Tommy Robinson as adviser
', '<p>The UK Independence Party looks set to be plunged into more leadership strife after Nigel Farage called on Gerard Batten to quit over his appointment of Tommy Robinson as an adviser.Mr Farage said he was “appalled” at the decision to make the controversial activist - real name Stephen Yaxley-Lennon - an adviser on rape gangs and prison conditions and reform.Mr Farage, who led Ukip on three occasions between 2006 and 2016, said Ukip would be “finished” as an electoral force if it continued in its current direction.However Mr Batten hit back saying that “Brexit is bigger than Nigel Farage’s ego” and that “Nigel has done nothing for Ukip in the past two years”.Mr Batten is now in planning over...</p>', 'https://www.telegraph.co.uk/politics/2018/11/23/tommy-robinson-named-adviser-ukip-leader-amid-debate-partys/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:48', '
Ukip civil war as Nigel Farage and party leader clash over giving Tommy Robinson membership 
', '<p>Gerard Batten, the Ukip leader, said he would approve of membership for English Defence League founder Tommy Robinson as a row with Nigel Farage worsened over the direction of the party.Mr Batten said Robinson would not be admitted to Ukip “in the near future" because it would require changes to the party''s rules but he insisted the controversial figure was not “far Right” and had his backing.Mr Farage said he was "really upset" over the suggestion Robinson could be allowed to join Ukip as he accused Mr Batten of marginalising the party.Mr Batten then warned Mr Farage to be “careful about criticising me” as he pointed to the former Ukip leader’s own connections with divisive characters.It...</p>', 'https://www.telegraph.co.uk/politics/2018/09/21/ukip-war-nigel-farage-gerard-batten-clash-tommy-robinson-membership/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:49', '
LibDem MP quits party whip to back Theresa May''s Brexit deal
', '', 'https://www.telegraph.co.uk/news/2018/12/06/libdem-mp-quits-party-whip-back-theresa-mays-brexit-deal/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:51', '
Nick Clegg wipes public Facebook profile, deleting Lib Dem and Brexit posts
', '<p>Nick Clegg has scrubbed all traces of his anti-Brexit activism from his public Facebook page as he begins a new job as the social network''s head of global affairs.Sir Nick, who joined Facebook last month after two years of intense campaigning to reverse the result of the EU referendum, wiped all his posts from the page, which was closed, some time in the last month.Among the posts deleted are multiple plugs for his book, How to Stop Brexit, and a call for MPs to "reject this damaging Brexit", as well as a post dated October 19 which explained his reasons for accepting his new job.Instead there is now only a picture of a rugged sunlit landscape and two pictures of himself, one of which appears...</p>', 'https://www.telegraph.co.uk/technology/2018/11/17/nick-clegg-wipes-public-facebook-profile-deleting-lib-dem-brexit/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:52', '
Peer ''told woman sleep with me and I will make you a Baroness'' as he faces suspension 
', '<p>A prominent peer told a woman "sleep with me and I will make you a Baroness", the Lords’ standards watchdog heard as he becomes the first Parliamentarian facing suspension over sexual harassment.Lord Lester of Herne Hill QC, the Liberal Democrat peer, faces suspension from the House of Lords until 2022 for sexually harassing a woman and "offering her corrupt inducements to become his mistress".The leading human rights lawyer, who was the architect of the UK''s race and sex equality laws, was under investigation by the parliamentary authorities over a historical allegation of sexual harassment.On Monday the House of Lords privileges and conduct committee recommended that Lord Lester should be...</p>', 'https://www.telegraph.co.uk/politics/2018/11/12/peer-faces-suspension-house-lords-alleged-sexual-harassment/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:54', '
SNP urged to rule out tax hike in Scottish Budget after figures show they got third largest funding rise
', '<p>The SNP''s Finance Minister has come under further pressure to rule out middle-class tax rises in this week''s Scottish Budget after it emerged he has received the UK''s third highest funding increase.The Scottish Tories highlighted official figures showing the Chancellor''s spending announcements have handed the SNP government an extra £1.6 billion for next year.They said the Treasury''s Red Book, produced with each UK Budget, showed the only spending areas to get a larger rise from Philip Hammond are the English NHS and transport.Murdo Fraser, their Shadow Finance Minister, said the figures demonstrated that Derek Mackay has enough spending money without having to further increase taxes on Wednesday....</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/snp-urged-rule-tax-hike-scottish-budget-figures-show-got-third/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:56', '
John Swinney and Scottish councils in blame game over school music tuition fees
', '<p>A blame game has erupted between John Swinney and Scottish council leaders over who is responsible for pricing out hundreds of children of the chance to learn a musical instrument.Mr Swinney, the Education Minister, told a Holyrood inquiry that only "some" local authorities "recognise the value" of not charging for instrumental music tuition.But he ruled out providing direct funding grants from central government to allow the other local authorities to abolish their charges.The Convention of Scottish Local Authorities (Cosla) blamed the SNP government''s "chronic underfunding" of councils, with £1.64 billion of real-terms cuts since 2011/12.Pressed that poor children are being priced out of...</p>', 'https://www.telegraph.co.uk/politics/2018/12/05/john-swinney-scottish-councils-blame-game-school-music-tuition/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:58', '
Derek Mackay accused of ignoring Scottish business after arguing another tax hike would not backfire
', '<p>The SNP''s Finance Minister has been accused of ignoring major employers'' warnings after arguing that another middle-class tax rise in next week''s Holyrood Budget would not backfire.The Scottish Tories said a series of businesses have warned about the damage caused by a growing income tax gap with England but Derek Mackay "isn''t listening to these experts."They hit out after Mr Mackay said his "sense" was that he could impose another income tax increase for the middle classes without hitting the economy and damaging revenues.He told the Financial Times that his decision to impose higher taxes on Scotland''s middle classes had not rebounded so far and argued there was still scope for further...</p>', 'https://www.telegraph.co.uk/politics/2018/12/05/derek-mackay-accused-ignoring-scottish-business-arguing-another/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:58', '
Quiz: are you a ‘normal’ guy?
', '', 'https://www.telegraph.co.uk/health-fitness/living-with-erectile-dysfunction/are-you-a-normal-guy/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:58', '
Why Madeira is perfect for an active holiday in the great outdoors
', '', 'https://www.telegraph.co.uk/travel/explore-madeira/outdoor-activities/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:59', '
Best of both worlds: solo river cruising
', '', 'https://www.telegraph.co.uk/travel/cruises/river-cruise-inspiration/solo-holidays/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:57:59', '
Hidden gems: the discreet charm of Greece’s smaller islands
', '', 'https://www.telegraph.co.uk/travel/destinations/europe/greece/captivating-holidays/small-greek-island-holidays/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:00', '
Scottish Tory ''waverers'' to announce Brexit vote decision after Theresa May lobbying campaign 
', '<p>Theresa May has personally lobbied sceptical Scottish Tory MPs to back her Brexit deal amid fears that more could disclose on Monday they intend to vote against it.John Lamont told the Telegraph he was one of several Scottish Conservatives to get private audiences with the Prime Minister in 10 Downing Street in which she sought to address their concerns.The Berwickshire, Roxburgh and Selkirk MP said he will make public on Monday whether he intends to back the agreement in tomorrow''s crucial vote after expressing major reservations.Douglas Ross, the Moray MP who ousted the SNP''s Angus Robertson in last year''s election, also plans to make clear his view on Monday. He told this newspaper last...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/scottish-tory-waverers-announce-brexit-vote-decision-theresa/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:02', '
Labour hatch plan to topple Theresa May and secure backing of disillusioned Tories and the DUP
', '<p>Labour has hatched a plan to topple Theresa May rather than directly target the Government, with insiders confirming senior figures have held discussions with the Democratic Unionist Party.Sources close to Jeremy Corbyn have told The Daily Telegraph that members of the two parties have discussed tabling a no confidence motion in the Prime Minister, in a move Labour hopes will unite the warring factions in Parliament against her.Whilst Sir Keir Starmer, the shadow Brexit Secretary, last week said it was “inevitable” that Labour would press for a no confidence vote in the Government, party insiders fear that doing so would cause Tory Brexiteers and Remainers to close ranks.Instead, Labour is...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/labour-hatch-plan-topple-theresa-may-secure-backing-disillusioned/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:03', '
Theresa May makes eleventh hour phone call to Donald Tusk as she considers postponing ''doomed'' vote
', '<p>Theresa May held 11th-hour crisis talks with EU leaders on Sunday as she agonised over whether to postpone Tuesday''s “doomed” vote on her Brexit deal.With time rapidly running out, Mrs May phoned Donald Tusk, the European Council president, to explain that MPs would kill off the deal – and possibly her premiership – unless Brussels could throw her a lifeline.Mrs May also called Leo Varadkar, the Irish Taoiseach, to discuss the vote and Thursday’s summit in Brussels. Mr Varadkar’s support is crucial if Mrs May is to win any concessions on  the Irish backstop – the biggest obstacle to getting her deal through Parliament. Even her closest allies were still unsure on Sunday whether she would postpone...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/theresa-may-makes-eleventh-hour-phone-call-donald-tusk-considers/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:04', '
Theresa May''s ''plan B'' could see second referendum that does not include option to remain in EU
', '<p>A radical plan for a second referendum that does not include the option to remain in the EU is being discussed as a possible “plan B” for Theresa May if she cannot get her Brexit deal through the Commons.Some May loyalists believe that a second referendum might be the “least worst” of several grim alternatives facing her if MPs block the deal on Tuesday or in a postponed vote.David Lidington, her de facto deputy, Business Secretary Greg Clark and Justice Secretary David Gauke are among those who believe a second referendum is increasingly likely.Mrs May could not, however, risk calling a referendum that could end up stopping Brexit altogether, having staked her party’s entire reputation on...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/theresa-mays-plan-b-could-see-second-referendum-does-not-include/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:06', '
EU official known as the ''monster'' of Brussels ''wants to take over as chief Brexit negotiator'' 
', '<p>A shadowy EU official who once described Brexit as "stupid" and is known in Brussels as "the monster" has reportedly told friends he wants to take charge of trade negotiations with the UK. Martin Selmayr, a former German lawyer who is infamous in EU circles for his Machiavellian management style, hopes to lead the Brexit talks after March 2019, according to the Sun on Sunday."Selmayr wants to send Barnier off into the horizon and leave it open who will head up trade negotiations with the UK," an EU source told the newspaper."He’s very keen to take that position for himself."A European Commission spokesman dismissed the claims, adding that Mr Selmayr already had a "very fulfilling" job as...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/eu-official-known-monster-brussels-wants-take-chief-brexit-negotiator/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:07', '
Boris Johnson says he has ''deep sense of personal responsibility'' for Brexit
', '<p>Boris Johnson has spoken passionately of his “deep sense of personal responsibility” for Brexit in a TV interview seen as the moment his Tory leadership campaign got into full swing.The former foreign secretary, sporting an uncharacteristically tidy haircut, refused to deny his intention to challenge Theresa May as he insisted he had an alternative Brexit plan that would break the current impasse.Mr Johnson dismissed as “nonsense” reports that he has already begun offering ministerial posts to MPs in return for backing him in a leadership contest.It came as Esther McVey, the former work and pensions secretary who also quit the Cabinet over Brexit, said she would give “serious” thought to running...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/boris-johnson-says-has-deep-sense-personal-responsibility-brexit/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:09', '
Crucial vote on Theresa May''s Brexit deal is ''100 per cent'' going ahead, insists Brexit Secretary 
', '<p>The vote on Theresa May’s Brexit deal is “100 per cent” going ahead on Tuesday as planned, the Brexit Secretary Stephen Barclay has said.Reports that Mrs May is contemplating delaying the vote until after a trip to Brussels this week are wide of the mark, Mr Barclay said, adding that there was still time to change the minds of MPs who say they will vote against the deal.To date, 109 Tory MPs have publicly criticised the deal, leaving the Government facing a heavy defeat when it is put to the Commons in two days time.Cabinet ministers have been putting pressure on Mrs May to postpone the vote until she has more chance of winning it, but Mr Barclay said: “The vote is going ahead.“It’s important...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/crucial-vote-theresa-mays-brexit-deal-100-percent-going-ahead/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:10', '
Theresa May losing grip as Conservative Party is rocked by Brexit resignations 
', '<p>Two members of the Government are resigning and a Cabinet minster is mulling whether to quit over Brexit this weekend as Theresa May’s administration appears to be disintegrating ahead of the most important vote of a generation.Government whips have given Conservative MPs until lunchtime on Sunday to set out how they will vote on Mrs May’s Brexit deal, in a desperate bid to judge the scale of a rebellion that threatens to bring down her government.Writing in The Telegraph, Will Quince MP, a member of the Defence Secretary’s ministerial team, announces he is quitting his government role, saying he wants to “implore the Prime Minister to go back to the European Union and find another way”.A...</p>', 'https://www.telegraph.co.uk/politics/2018/12/08/theresa-may-losing-grip-conservative-party-rocked-brexit-resignations/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:12', '
Tony Blair asked government officials to keep lucrative deals a secret
', '<p>Tony Blair personally asked government officials to keep details of lucrative post-Downing Street advisory work hidden from the public, The Telegraph can disclose.In a letter sent the year after he stepped down as prime minister, Mr Blair insisted that any contracts he struck on behalf of his new consultancy firm should be kept “confidential” to protect his new clients, including foreign governments and major international companies.Following his intervention, the official watchdog that vets the jobs ministers take up after leaving office quietly agreed to avoid publishing details about Tony Blair Associates that would “attract unnecessary attention”. It never published the names of its clients,...</p>', 'https://www.telegraph.co.uk/politics/2018/12/08/tony-blair-asked-government-officials-keep-lucrative-deals-secret/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:14', '
Fax machines will be banned across the NHS under radical plans to overhaul outdated technology
', '<p>Fax machines will be banned across the NHS under radical plans to overhaul outdated technology and IT systems, The Sunday Telegraph can disclose.Matt Hancock, the Health secretary, banned hospital trusts from buying fax machines on Friday and ordered them to be phased out completely by April 2020.NHS Trusts will instead be required to invest in new technology to replace any outdated systems, using £200million of Government cash set aside for modernisation earlier this year.Mr Hancock told The Sunday Telegraph: "Because I love the NHS, I want to bring it into the 21st century and use the very best technology available. We''ve got to get the basics right, like having computers that work and getting...</p>', 'https://www.telegraph.co.uk/politics/2018/12/08/faxmachines-will-banned-across-nhs-radical-plans-overhaul-outdated/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:15', '
Nigel Farage unveils plan to form new party to fight ''biggest battle yet'' for independence from EU
', '<p>Nigel Farage has said it is his "destiny" to fight for Brexit as he unveils his plans to launch a new political party to fight next year''s European Parliament elections if the Government delays Britain''s exit from the European Union.The former leader of the UK Independence Party told The Sunday Telegraph that he believed he had "not fought my biggest battle yet" and would relish the battle at May''s Euro elections, which he expects to be held if Brexit is delayed.Talks have been going on for a number of months about his new party but have been stepped in the past fortnight as the full detail of Theresa May''s Brexit deal has emerged.Mr Farage, 54, said he had held talks with a number of high...</p>', 'https://www.telegraph.co.uk/politics/2018/12/08/nigel-farage-unveils-plan-form-new-party-fight-biggest-battle/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:17', '
Brexit deal poll: Cabinet members who back May''s deal out of touch with voters
', '<p>Only a minority of voters in the constituencies of Cabinet minsters who are backing Theresa May''s deal want them to accept it, new polling has found.A mass study of the views of 10,000 voters by BMG Research found that one in two voters disapprove of the deal, with just one in four in favour.In general just over half of the electorate - 53 per cent - want their MP to vote against the deal and only 37 per cent want their MP to vote for it. Ten per cent said their MP should abstain.The BMG study for pro-Brexit campaign group Change Britain shows that 63 per cent of voters across the country do not want their MP to vote for the deal.It found that there are 147 Conservative MPs with constituencies...</p>', 'https://www.telegraph.co.uk/politics/2018/12/08/brexit-deal-poll-cabinet-members-back-mays-deal-touch-voters/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:18', '
Warnings of no-deal ports chaos are ''misleading'', industry boss says
', '<p>Warnings of a “logjam” at Britain’s ports as a result of a no-deal Brexit are misleading, a senior representative of the industry has said.It comes after Philip Hammond, the Chancellor, said that ports would face chaos if the UK left the EU without a deal and would take “years” to adapt.But Tim Morris, the chief executive of UK Major Ports Group, the trade body, said: “The UK’s port sector is a resilient, adaptable and highly competitive one, offering customers a range of options."We will work through the challenges of Brexit as we have done with huge changes throughout the centuries.” In a letter to The Daily Telegraph on behalf of port operators responsible for 75 per cent of the UK’s seaborne...</p>', 'https://www.telegraph.co.uk/politics/2018/12/07/warnings-no-deal-ports-chaos-misleading-industry-boss-says/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:20', '
Theresa May told to quit by Cabinet ministers if her Brexit deal falls and she fails to get better terms from EU
', '<p>Theresa May has been warned by Cabinet ministers she will have to quit if her Brexit deal is defeated in the Commons next week and she fails to secure better terms from the EU, the Telegraph can disclose.Ministers believe that there is “zero” chance of her deal, which has been publicly criticised by more than 100 Tory MPs, passing in a crunch Commons vote on Tuesday.One Cabinet minister told the Telegraph “she [Mrs May] will fall” if she is defeated and then fails to go back to Brussels to fundamentally renegotiate the EU withdrawal agreement.It came as Iain Duncan Smith, a Eurosceptic Tory MP and former Conservative leader, warned for the first time that Mrs May could have to go if she and...</p>', 'https://www.telegraph.co.uk/politics/2018/12/07/theresa-may-told-quit-cabinet-ministers-brexit-deal-falls-fails/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:22', '
May''s deal, no deal or Remain: is your constituency one of just two to back the Prime Minister?
', '<p>It is not clear what the next steps would be should Mrs May be defeated in the meaningful vote on her withdrawal deal on Tuesday - something that looks increasingly likely to happen based on the parliamentary maths.MPs on all sides are at great pains to work out what course of action is best representative of the "will of the people", with only the EU referendum result to go on.YouGov have attempted to help out here by modelling opinion on May''s deal, no deal and Remain in every constituency in England, Scotland and Wales (sorry Northern Ireland).You can see the results for your constituency in the table below. Based on first preferences alone, Remain wins in 600 areas, while no deal triumphs...</p>', 'https://www.telegraph.co.uk/politics/2018/12/07/mays-deal-no-deal-remain-constituency-one-just-two-back-prime/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:23', '
As the Brexit ''meaningful vote'' in Parliament is delayed - what are the next steps for Theresa May?
', '<p>After months of negotiations, the Brexit deal was due to be voted upon tomorrow, in order for the United Kingdom''s Parliament to approve or reject Theresa May''s controversial plan.However, the prime minister has dramatically called off the "meaningful vote", today, in the face of what had been expected to be a significant defeat at the hands of rebel MPs.A Government source confirmed that the vote was being pulled, with the Prime Minister due to inform the House of Commons in an oral statement at 3.30pm where she is expected to confirm that she intends to seek further concessions from Brussels to try to win over rebellious backbenchers.But what does all this mean for the "meaningful vote"...</p>', 'https://www.telegraph.co.uk/politics/2018/12/10/time-does-parliament-vote-brexit-deal-tomorrow-meaningful-vote/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:24', '
Brexit latest news: Major ports to be disrupted for six months under no deal
', '<p>Major ports could suffer disruption for up to six months under a no-deal scenario, the Government has told industry leaders.Revised Brexit assessments published on Friday warned that access through Dover and Folkestone could be reduced for significantly longer than first feared.Matt Hancock, the Health Secretary, has written to health and care providers setting out contingency plans...</p>', 'https://www.telegraph.co.uk/politics/2018/12/07/brexit-latest-news-ministers-fan-across-country-last-effort/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:26', '
Brexit explained: All your questions answered about the UK leaving the EU  
', '<p>Should the United Kingdom remain a member of the European Union or leave the European Union? The answer given by the people of Great Britain, Northern Ireland and Gibraltar on the 23rd June 2016 to that question has kickstarted a process that has sparked many more questions.The questions have ranged across a wide variety of areas, ranging from the origin of the Brexit vote to queries about the implications of what has come out of the negotiations over Britain''s withdrawal. Politicians have had a lot to learn about what is at stake in this process. No longer should they mix up the single market with the customs union.We have knuckled down and sought to provide clarity on all the key issues vexing...</p>', 'https://www.telegraph.co.uk/politics/0/brexit-explained-questions-answered-uk-leaving-eu/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:27', '
Who could replace Theresa May as the next Tory leader and Prime Minister? Runners and riders
', '<p>Theresa May''s leadership is under intense pressure after she dramatically called off the crucial "meaningful vote" on her controversial Brexit deal.The Prime Minister apparently made the decision after it became clear she was due to face significant defeat at the hands of rebel MPs on Tuesday, leaving her political future in doubt. A Government source confirmed that the vote was being pulled, with the Prime Minister due to inform the House of Commons in an oral statement at 3.30pm.Mrs May''s hastily-arranged oral statement is widely expected to confirm that she intends to seek further concessions from Brussels to try to win over rebellious backbenchers.But as the Brexit chaos continues and rumours...</p>', 'https://www.telegraph.co.uk/politics/2018/12/09/runners-riders-could-replace-theresa-may-forced-downing-street/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:28', '
Did Vote Leave''s overspending really win the EU referendum?
', '<p>British expats will present evidence to the High Court today that claims it is "very likely" that Vote Leave''s overspending on Facebook ads swung the referendum towards Leave.The goal of the case is to have the result of the 2016 referendum reversed and for Theresa May to revoke Article 50.The evidence in question comes in the form of an expert opinion from Dr Philip Howard, Director of the Oxford Internet Institute and a Professor of Internet Studies at Oxford University.In it Dr Howard claims that it is likely 800,000 people''s votes were directly influenced by adverts paid for by Vote Leave after the campaign had reached its spending limit. The methodology used to arrive at this large figure,...</p>', 'https://www.telegraph.co.uk/politics/2018/12/07/did-vote-leaves-overspending-really-win-eu-referendum/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:29', '
John McDonnell''s "lynching" comments incited violence and compromised my safety, says Esther McVey
', '<p>Esther McVey has accused John McDonnell of inciting violence against her, saying his “lynching” comments made it unsafe for her to walk the streets of her constituency.Labour’s shadow chancellor was criticised in 2014 for repeating comments calling the former work and pensions a “b****” who deserved to be “lynched”.Describing McDonnell as a “bully”, the Tatton MP, 51, told the Telegraph: “Labour always made it very personal against me because I was a Liverpudlian who dared to become a Conservative. Then I stood and after 10 years I won and they couldn’t believe that would happen in a Merseyside area. Then I was put in charge of benefits.“When I got the lynching comments I thought - you haven’t...</p>', 'https://www.telegraph.co.uk/politics/2018/12/06/john-mcdonnells-lynching-comments-incited-violence-compromised/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:31', '
Esther McVey: I knew Theresa May''s Brexit deal was terrible but my Cabinet colleagues just crumbled
', '<p>Esther McVey has revealed how demanding a vote on Theresa May’s “terrible” Brexit deal prompted a “meltdown” in Cabinet as colleagues “crumbled” around her.The former Work and Pensions secretary revealed how she was “shouted down” by Cabinet secretary Mark Sedwill, Britain’s top civil servant, after asking for a vote on the biggest decision taken by politicians in nearly half a century.Denying suggestions she had been “emotional” during the tense exchanges at last month’s five-hour Cabinet showdown, which resulted in her resigning along with Brexit Secretary Dominic Raab, the Liverpudlian MP told the Telegraph: “No one in Cabinet supported me. I was astounded. What I was asking for was a vote...</p>', 'https://www.telegraph.co.uk/politics/2018/12/06/esther-mcvey-knew-theresa-mays-brexit-deal-terrible-cabinet/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:33', '
A day when Theresa May’s indecision had even loyalists wondering what will happen next 
', '<p>Theresa May had started the day ­optimistically, suggesting to Today ­programme listeners that she could still win the vote on her Brexit deal, which would definitely go ahead next Tuesday.With a little sleight of hand over the troublesome backstop she would persuade rebel Tory MPs that everything would be all right because they would “have a choice” about whether to use it.Just 90 minutes after she came off air, however, the mask had slipped. ­Either side of 10am a succession of ­Cabinet ministers received phone calls from Downing Street calling them to an emergency meeting to discuss the Brexit deal vote.Only when they received an email minutes later did they know who else would be attending...</p>', 'https://www.telegraph.co.uk/politics/2018/12/06/day-theresa-mays-indecision-had-even-loyalists-wondering-will/');
INSERT INTO wcc.telegraph_detail (in_time, title, cotent, href) VALUES ('2018-12-11 01:58:34', '
Size of task facing Theresa May  becomes clear as footage shows chief whip failing to get Tory MP on board
', '', 'https://www.telegraph.co.uk/politics/2018/12/06/size-task-facing-theresamay-becomes-clear-footage-shows-chief/');